security:
  oauth2:
    client:
      client-id: client1
      client-secret: secret1
      user-authorization-uri: http://127.0.0.1:8100/server/oauth/authorize
      access-token-uri: http://127.0.0.1:8100/server/oauth/token
    resource:
      jwt:
        key-uri:  http://127.0.0.1:8100/server/oauth/token_key
server:
  port: 8200
  context-path: /oa
